import type { Account, JournalEntry } from "./types";

const DAY_MS = 1000 * 60 * 60 * 24;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY_MS).toISOString();

export const SEED_ACCOUNTS: Account[] = [
  { id: "acc-1000", code: "1000", name: "Cash in Hand", type: "asset" },
  { id: "acc-1010", code: "1010", name: "Bank Account", type: "asset" },
  { id: "acc-1100", code: "1100", name: "GST Input Credit", type: "asset", description: "Recoverable tax paid on purchases and services." },
  { id: "acc-2000", code: "2000", name: "Accounts Payable", type: "liability" },
  { id: "acc-2010", code: "2010", name: "GST Payable", type: "liability", description: "Tax collected on taxable income, owed to the tax authority." },
  { id: "acc-3000", code: "3000", name: "School Fund", type: "equity" },
  { id: "acc-4000", code: "4000", name: "Tuition Fee Income", type: "income" },
  { id: "acc-4010", code: "4010", name: "Transport Fee Income", type: "income" },
  { id: "acc-4020", code: "4020", name: "Hostel Fee Income", type: "income" },
  { id: "acc-4030", code: "4030", name: "Other Income", type: "income" },
  { id: "acc-5000", code: "5000", name: "Salaries & Wages", type: "expense" },
  { id: "acc-5010", code: "5010", name: "Utilities Expense", type: "expense" },
  { id: "acc-5020", code: "5020", name: "Maintenance & Repairs", type: "expense" },
  { id: "acc-5030", code: "5030", name: "Supplies & Stationery", type: "expense" },
  { id: "acc-5040", code: "5040", name: "Professional & Consultancy Fees", type: "expense" },
  { id: "acc-5050", code: "5050", name: "Miscellaneous Expenses", type: "expense" },
];

function line(accountId: string, debit: number, credit: number, description?: string) {
  return { id: `ln-${accountId}-${Math.random().toString(36).slice(2, 8)}`, accountId, debit, credit, description };
}

export function buildSeedJournalEntries(): JournalEntry[] {
  let seq = 0;
  const nextNumber = () => `JE-2026-${String(++seq).padStart(4, "0")}`;
  const entries: Array<Omit<JournalEntry, "entryNumber">> = [
    {
      id: "je-1",
      date: daysAgo(178),
      narration: "Opening balance",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(178),
      lines: [line("acc-1010", 500000, 0, "Opening bank balance"), line("acc-3000", 0, 500000, "Opening school fund")],
    },
    {
      id: "je-2",
      date: daysAgo(170),
      narration: "Tuition fee collection — April",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(170),
      lines: [line("acc-1010", 180000, 0), line("acc-4000", 0, 180000)],
    },
    {
      id: "je-3",
      date: daysAgo(165),
      narration: "Staff salaries — April",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(165),
      lines: [line("acc-5000", 150000, 0), line("acc-1010", 0, 150000)],
    },
    {
      id: "je-4",
      date: daysAgo(150),
      narration: "Electricity & water bill — April",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(150),
      lines: [line("acc-5010", 12000, 0), line("acc-1010", 0, 12000)],
    },
    {
      id: "je-5",
      date: daysAgo(140),
      narration: "Tuition fee collection — May",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(140),
      lines: [line("acc-1010", 195000, 0), line("acc-4000", 0, 195000)],
    },
    {
      id: "je-6",
      date: daysAgo(135),
      narration: "Transport fee collection — Term 1",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(135),
      lines: [line("acc-1010", 45000, 0), line("acc-4010", 0, 45000)],
    },
    {
      id: "je-7",
      date: daysAgo(132),
      narration: "Staff salaries — May",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(132),
      lines: [line("acc-5000", 150000, 0), line("acc-1010", 0, 150000)],
    },
    {
      id: "je-8",
      date: daysAgo(120),
      narration: "Building maintenance — repainting block B",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(120),
      lines: [line("acc-5020", 25000, 0), line("acc-1010", 0, 25000)],
    },
    {
      id: "je-9",
      date: daysAgo(105),
      narration: "Hostel fee collection — Term 1",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(105),
      lines: [line("acc-1010", 32000, 0), line("acc-4020", 0, 32000)],
    },
    {
      id: "je-10",
      date: daysAgo(95),
      narration: "External auditor consultancy fee",
      status: "posted",
      gstApplicable: true,
      gstAmount: 9000,
      createdAt: daysAgo(95),
      lines: [line("acc-5040", 50000, 0), line("acc-1100", 9000, 0, "Input GST @ 18%"), line("acc-1010", 0, 59000)],
    },
    {
      id: "je-11",
      date: daysAgo(80),
      narration: "Hall rental income — community event",
      status: "posted",
      gstApplicable: true,
      gstAmount: 3600,
      createdAt: daysAgo(80),
      lines: [line("acc-1010", 23600, 0), line("acc-4030", 0, 20000), line("acc-2010", 0, 3600, "Output GST @ 18%")],
    },
    {
      id: "je-12",
      date: daysAgo(70),
      narration: "Tuition fee collection — June",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(70),
      lines: [line("acc-1010", 210000, 0), line("acc-4000", 0, 210000)],
    },
    {
      id: "je-13",
      date: daysAgo(65),
      narration: "Staff salaries — June",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(65),
      lines: [line("acc-5000", 150000, 0), line("acc-1010", 0, 150000)],
    },
    {
      id: "je-14",
      date: daysAgo(50),
      narration: "Stationery & lab supplies restock",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(50),
      lines: [line("acc-5030", 8000, 0), line("acc-1000", 0, 8000)],
    },
    {
      id: "je-15",
      date: daysAgo(40),
      narration: "Transport fee collection — Term 2",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(40),
      lines: [line("acc-1010", 48000, 0), line("acc-4010", 0, 48000)],
    },
    {
      id: "je-16",
      date: daysAgo(30),
      narration: "Tuition fee collection — July",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(30),
      lines: [line("acc-1010", 220000, 0), line("acc-4000", 0, 220000)],
    },
    {
      id: "je-17",
      date: daysAgo(25),
      narration: "Staff salaries — July",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(25),
      lines: [line("acc-5000", 150000, 0), line("acc-1010", 0, 150000)],
    },
    {
      id: "je-18",
      date: daysAgo(18),
      narration: "IT support & software renewal",
      status: "posted",
      gstApplicable: true,
      gstAmount: 4500,
      createdAt: daysAgo(18),
      lines: [line("acc-5040", 25000, 0), line("acc-1100", 4500, 0, "Input GST @ 18%"), line("acc-1010", 0, 29500)],
    },
    {
      id: "je-19",
      date: daysAgo(10),
      narration: "Petty cash — miscellaneous office expenses",
      status: "posted",
      gstApplicable: false,
      createdAt: daysAgo(10),
      lines: [line("acc-5050", 5000, 0), line("acc-1000", 0, 5000)],
    },
    {
      id: "je-20",
      date: daysAgo(3),
      narration: "Tuition fee collection — August (pending reconciliation)",
      status: "draft",
      gstApplicable: false,
      createdAt: daysAgo(3),
      lines: [line("acc-1010", 240000, 0), line("acc-4000", 0, 240000)],
    },
    {
      id: "je-21",
      date: daysAgo(1),
      narration: "Staff salaries — August (awaiting approval)",
      status: "draft",
      gstApplicable: false,
      createdAt: daysAgo(1),
      lines: [line("acc-5000", 152000, 0), line("acc-1010", 0, 152000)],
    },
  ];

  return entries.map((e) => ({ ...e, entryNumber: nextNumber() }));
}
