import type { AdmissionApplication, Student } from "./types";

const DAY_MS = 1000 * 60 * 60 * 24;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY_MS).toISOString();
const yearsAgo = (n: number) => new Date(Date.now() - n * DAY_MS * 365).toISOString();

let seq = 1;
function admissionNumber(): string {
  return `EDU-2026-${String(seq++).padStart(4, "0")}`;
}

function baseGuardian(name: string, relation: "father" | "mother", phone: string) {
  return { id: `g-${Math.random().toString(36).slice(2, 8)}`, name, relation, phone };
}

export const SEED_STUDENTS: Student[] = [
  {
    id: "stu-1",
    admissionNumber: admissionNumber(),
    firstName: "Riya",
    lastName: "Kapoor",
    photoUrl: null,
    dateOfBirth: yearsAgo(13),
    gender: "female",
    className: "Grade 8",
    section: "A",
    rollNumber: "8A-01",
    status: "active",
    admissionDate: yearsAgo(3),
    address: "12 Lakeview Road, Bengaluru",
    guardians: [baseGuardian("Anil Kapoor", "father", "+91 98450 10001"), baseGuardian("Sunita Kapoor", "mother", "+91 98450 10002")],
    emergencyContact: { name: "Anil Kapoor", relation: "Father", phone: "+91 98450 10001" },
    medical: { bloodGroup: "O+", allergies: "Peanuts", conditions: "", medications: "" },
    transport: { required: true, routeName: "Route 4 - North Loop", pickupPoint: "Lakeview Circle" },
    hostel: { required: false },
    documents: [],
  },
  {
    id: "stu-2",
    admissionNumber: admissionNumber(),
    firstName: "Aarav",
    lastName: "Sharma",
    photoUrl: null,
    dateOfBirth: yearsAgo(15),
    gender: "male",
    className: "Grade 10",
    section: "B",
    rollNumber: "10B-07",
    status: "active",
    admissionDate: yearsAgo(5),
    address: "44 MG Road, Bengaluru",
    guardians: [baseGuardian("Rakesh Sharma", "father", "+91 98450 20001")],
    emergencyContact: { name: "Rakesh Sharma", relation: "Father", phone: "+91 98450 20001" },
    medical: { bloodGroup: "B+", allergies: "", conditions: "Asthma", medications: "Inhaler as needed" },
    transport: { required: false },
    hostel: { required: true, hostelName: "Boys Hostel A", roomNumber: "204" },
    documents: [],
  },
  {
    id: "stu-3",
    admissionNumber: admissionNumber(),
    firstName: "Sara",
    lastName: "Thomas",
    photoUrl: null,
    dateOfBirth: yearsAgo(9),
    gender: "female",
    className: "Grade 3",
    section: "A",
    rollNumber: "3A-14",
    status: "active",
    admissionDate: yearsAgo(1),
    address: "7 Church Street, Bengaluru",
    guardians: [baseGuardian("Thomas Varghese", "father", "+91 98450 30001"), baseGuardian("Anita Thomas", "mother", "+91 98450 30002")],
    emergencyContact: { name: "Anita Thomas", relation: "Mother", phone: "+91 98450 30002" },
    medical: { bloodGroup: "A+", allergies: "", conditions: "", medications: "" },
    transport: { required: true, routeName: "Route 1 - City Loop", pickupPoint: "Church Street Junction" },
    hostel: { required: false },
    documents: [],
  },
  {
    id: "stu-4",
    admissionNumber: admissionNumber(),
    firstName: "Vikram",
    lastName: "Rao",
    photoUrl: null,
    dateOfBirth: yearsAgo(17),
    gender: "male",
    className: "Grade 12",
    section: "A",
    rollNumber: "12A-02",
    status: "active",
    admissionDate: yearsAgo(7),
    address: "9 Residency Road, Bengaluru",
    guardians: [baseGuardian("Suresh Rao", "father", "+91 98450 40001")],
    emergencyContact: { name: "Suresh Rao", relation: "Father", phone: "+91 98450 40001" },
    medical: { bloodGroup: "AB+", allergies: "", conditions: "", medications: "" },
    transport: { required: false },
    hostel: { required: false },
    documents: [],
  },
  {
    id: "stu-5",
    admissionNumber: admissionNumber(),
    firstName: "Meher",
    lastName: "Khan",
    photoUrl: null,
    dateOfBirth: yearsAgo(11),
    gender: "female",
    className: "Grade 6",
    section: "C",
    rollNumber: "6C-09",
    status: "inactive",
    admissionDate: yearsAgo(2),
    address: "21 Brigade Road, Bengaluru",
    guardians: [baseGuardian("Imran Khan", "father", "+91 98450 50001")],
    emergencyContact: { name: "Imran Khan", relation: "Father", phone: "+91 98450 50001" },
    medical: { bloodGroup: "O-", allergies: "Penicillin", conditions: "", medications: "" },
    transport: { required: true, routeName: "Route 2 - East Loop", pickupPoint: "Brigade Junction" },
    hostel: { required: false },
    documents: [],
  },
  {
    id: "stu-6",
    admissionNumber: admissionNumber(),
    firstName: "Devika",
    lastName: "Menon",
    photoUrl: null,
    dateOfBirth: yearsAgo(18),
    gender: "female",
    className: "Grade 12",
    section: "B",
    rollNumber: "12B-11",
    status: "graduated",
    admissionDate: yearsAgo(8),
    address: "3 Cunningham Road, Bengaluru",
    guardians: [baseGuardian("Ravi Menon", "father", "+91 98450 60001")],
    emergencyContact: { name: "Ravi Menon", relation: "Father", phone: "+91 98450 60001" },
    medical: { bloodGroup: "A-", allergies: "", conditions: "", medications: "" },
    transport: { required: false },
    hostel: { required: false },
    documents: [],
  },
];

export const SEED_ADMISSIONS: AdmissionApplication[] = [
  {
    id: "adm-1",
    applicationNumber: "ADM-2026-0001",
    applicantFirstName: "Ishaan",
    applicantLastName: "Verma",
    dateOfBirth: yearsAgo(6),
    gender: "male",
    guardianName: "Neeraj Verma",
    guardianPhone: "+91 98450 70001",
    appliedClass: "Grade 1",
    stage: "inquiry",
    submittedAt: daysAgo(3),
  },
  {
    id: "adm-2",
    applicationNumber: "ADM-2026-0002",
    applicantFirstName: "Ananya",
    applicantLastName: "Iyer",
    dateOfBirth: yearsAgo(10),
    gender: "female",
    guardianName: "Kavitha Iyer",
    guardianPhone: "+91 98450 70002",
    guardianEmail: "kavitha.iyer@gmail.com",
    appliedClass: "Grade 5",
    stage: "registration",
    submittedAt: daysAgo(8),
    address: "22 Malleshwaram 12th Cross, Bengaluru",
    previousSchool: "Greenwood Public School",
    registeredAt: daysAgo(6),
  },
  {
    id: "adm-3",
    applicationNumber: "ADM-2026-0003",
    applicantFirstName: "Rehan",
    applicantLastName: "Ahmed",
    dateOfBirth: yearsAgo(14),
    gender: "male",
    guardianName: "Salim Ahmed",
    guardianPhone: "+91 98450 70003",
    appliedClass: "Grade 9",
    stage: "entrance_exam",
    submittedAt: daysAgo(12),
    address: "5 Frazer Town, Bengaluru",
    registeredAt: daysAgo(11),
    examDate: daysAgo(2),
    examScore: 78,
    examStatus: "completed",
  },
  {
    id: "adm-4",
    applicationNumber: "ADM-2026-0004",
    applicantFirstName: "Kavya",
    applicantLastName: "Reddy",
    dateOfBirth: yearsAgo(8),
    gender: "female",
    guardianName: "Suresh Reddy",
    guardianPhone: "+91 98450 70004",
    guardianEmail: "suresh.reddy@gmail.com",
    appliedClass: "Grade 3",
    stage: "interview",
    submittedAt: daysAgo(15),
    address: "18 Indiranagar 100ft Road, Bengaluru",
    registeredAt: daysAgo(14),
    examDate: daysAgo(9),
    examScore: 82,
    examStatus: "completed",
    interviewDate: daysAgo(1),
    interviewerName: "Meera Iyer",
  },
  {
    id: "adm-5",
    applicationNumber: "ADM-2026-0005",
    applicantFirstName: "Arnav",
    applicantLastName: "Gupta",
    dateOfBirth: yearsAgo(11),
    gender: "male",
    guardianName: "Rohit Gupta",
    guardianPhone: "+91 98450 70005",
    appliedClass: "Grade 6",
    stage: "fee_collection",
    submittedAt: daysAgo(20),
    address: "9 Koramangala 5th Block, Bengaluru",
    registeredAt: daysAgo(19),
    examDate: daysAgo(14),
    examScore: 88,
    examStatus: "completed",
    interviewDate: daysAgo(10),
    interviewerName: "Meera Iyer",
    interviewRating: 5,
    interviewRemarks: "Confident and articulate; strong fit.",
    decision: "selected",
    decisionRemarks: "Excellent exam and interview performance.",
    decidedAt: daysAgo(9),
    admissionFeeAmount: 2000,
  },
  {
    id: "adm-6",
    applicationNumber: "ADM-2026-0006",
    applicantFirstName: "Zoya",
    applicantLastName: "Khan",
    dateOfBirth: yearsAgo(15),
    gender: "female",
    guardianName: "Imran Khan",
    guardianPhone: "+91 98450 70006",
    appliedClass: "Grade 10",
    stage: "waitlisted",
    submittedAt: daysAgo(18),
    address: "31 Jayanagar 9th Block, Bengaluru",
    registeredAt: daysAgo(17),
    examDate: daysAgo(12),
    examScore: 71,
    examStatus: "completed",
    interviewDate: daysAgo(7),
    interviewerName: "Meera Iyer",
    interviewRating: 3,
    interviewRemarks: "Solid application; Grade 10 has very limited seats this year.",
    decision: "waitlisted",
    decisionRemarks: "Waitlisted — Grade 10 is nearly at capacity. Will be offered a seat if one frees up.",
    decidedAt: daysAgo(6),
  },
  {
    id: "adm-7",
    applicationNumber: "ADM-2026-0007",
    applicantFirstName: "Vihaan",
    applicantLastName: "Malhotra",
    dateOfBirth: yearsAgo(13),
    gender: "male",
    guardianName: "Anil Malhotra",
    guardianPhone: "+91 98450 70007",
    appliedClass: "Grade 8",
    stage: "rejected",
    submittedAt: daysAgo(25),
    address: "14 HSR Layout Sector 2, Bengaluru",
    registeredAt: daysAgo(24),
    examDate: daysAgo(19),
    examScore: 42,
    examStatus: "completed",
    interviewDate: daysAgo(15),
    interviewerName: "Meera Iyer",
    interviewRating: 2,
    interviewRemarks: "Below grade-level readiness in core subjects.",
    decision: "rejected",
    decisionRemarks: "Did not meet the grade-level readiness benchmark for Grade 8.",
    decidedAt: daysAgo(14),
  },
];
