import type { AdmissionApplication, Student } from "./types";

const DAY_MS = 1000 * 60 * 60 * 24;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY_MS).toISOString();
const yearsAgo = (n: number) => new Date(Date.now() - n * DAY_MS * 365).toISOString();

let seq = 1;
function admissionNumber(): string {
  return `EDU-2026-${String(seq++).padStart(4, "0")}`;
}

function baseGuardian(name: string, relation: "father" | "mother", phone: string) {
  return { id: `g-${Math.random().toString(36).slice(2, 8)}`, name, relation, phone };
}

export const SEED_STUDENTS: Student[] = [
  {
    id: "stu-1",
    admissionNumber: admissionNumber(),
    firstName: "Riya",
    lastName: "Kapoor",
    photoUrl: null,
    dateOfBirth: yearsAgo(13),
    gender: "female",
    className: "Grade 8",
    section: "A",
    rollNumber: "8A-01",
    status: "active",
    admissionDate: yearsAgo(3),
    address: "12 Lakeview Road, Bengaluru",
    guardians: [baseGuardian("Anil Kapoor", "father", "+91 98450 10001"), baseGuardian("Sunita Kapoor", "mother", "+91 98450 10002")],
    emergencyContact: { name: "Anil Kapoor", relation: "Father", phone: "+91 98450 10001" },
    medical: { bloodGroup: "O+", allergies: "Peanuts", conditions: "", medications: "" },
    transport: { required: true, routeName: "Route 4 - North Loop", pickupPoint: "Lakeview Circle" },
    hostel: { required: false },
    documents: [],
  },
  {
    id: "stu-2",
    admissionNumber: admissionNumber(),
    firstName: "Aarav",
    lastName: "Sharma",
    photoUrl: null,
    dateOfBirth: yearsAgo(15),
    gender: "male",
    className: "Grade 10",
    section: "B",
    rollNumber: "10B-07",
    status: "active",
    admissionDate: yearsAgo(5),
    address: "44 MG Road, Bengaluru",
    guardians: [baseGuardian("Rakesh Sharma", "father", "+91 98450 20001")],
    emergencyContact: { name: "Rakesh Sharma", relation: "Father", phone: "+91 98450 20001" },
    medical: { bloodGroup: "B+", allergies: "", conditions: "Asthma", medications: "Inhaler as needed" },
    transport: { required: false },
    hostel: { required: true, hostelName: "Boys Hostel A", roomNumber: "204" },
    documents: [],
  },
  {
    id: "stu-3",
    admissionNumber: admissionNumber(),
    firstName: "Sara",
    lastName: "Thomas",
    photoUrl: null,
    dateOfBirth: yearsAgo(9),
    gender: "female",
    className: "Grade 3",
    section: "A",
    rollNumber: "3A-14",
    status: "active",
    admissionDate: yearsAgo(1),
    address: "7 Church Street, Bengaluru",
    guardians: [baseGuardian("Thomas Varghese", "father", "+91 98450 30001"), baseGuardian("Anita Thomas", "mother", "+91 98450 30002")],
    emergencyContact: { name: "Anita Thomas", relation: "Mother", phone: "+91 98450 30002" },
    medical: { bloodGroup: "A+", allergies: "", conditions: "", medications: "" },
    transport: { required: true, routeName: "Route 1 - City Loop", pickupPoint: "Church Street Junction" },
    hostel: { required: false },
    documents: [],
  },
  {
    id: "stu-4",
    admissionNumber: admissionNumber(),
    firstName: "Vikram",
    lastName: "Rao",
    photoUrl: null,
    dateOfBirth: yearsAgo(17),
    gender: "male",
    className: "Grade 12",
    section: "A",
    rollNumber: "12A-02",
    status: "active",
    admissionDate: yearsAgo(7),
    address: "9 Residency Road, Bengaluru",
    guardians: [baseGuardian("Suresh Rao", "father", "+91 98450 40001")],
    emergencyContact: { name: "Suresh Rao", relation: "Father", phone: "+91 98450 40001" },
    medical: { bloodGroup: "AB+", allergies: "", conditions: "", medications: "" },
    transport: { required: false },
    hostel: { required: false },
    documents: [],
  },
  {
    id: "stu-5",
    admissionNumber: admissionNumber(),
    firstName: "Meher",
    lastName: "Khan",
    photoUrl: null,
    dateOfBirth: yearsAgo(11),
    gender: "female",
    className: "Grade 6",
    section: "C",
    rollNumber: "6C-09",
    status: "inactive",
    admissionDate: yearsAgo(2),
    address: "21 Brigade Road, Bengaluru",
    guardians: [baseGuardian("Imran Khan", "father", "+91 98450 50001")],
    emergencyContact: { name: "Imran Khan", relation: "Father", phone: "+91 98450 50001" },
    medical: { bloodGroup: "O-", allergies: "Penicillin", conditions: "", medications: "" },
    transport: { required: true, routeName: "Route 2 - East Loop", pickupPoint: "Brigade Junction" },
    hostel: { required: false },
    documents: [],
  },
  {
    id: "stu-6",
    admissionNumber: admissionNumber(),
    firstName: "Devika",
    lastName: "Menon",
    photoUrl: null,
    dateOfBirth: yearsAgo(18),
    gender: "female",
    className: "Grade 12",
    section: "B",
    rollNumber: "12B-11",
    status: "graduated",
    admissionDate: yearsAgo(8),
    address: "3 Cunningham Road, Bengaluru",
    guardians: [baseGuardian("Ravi Menon", "father", "+91 98450 60001")],
    emergencyContact: { name: "Ravi Menon", relation: "Father", phone: "+91 98450 60001" },
    medical: { bloodGroup: "A-", allergies: "", conditions: "", medications: "" },
    transport: { required: false },
    hostel: { required: false },
    documents: [],
  },
];

export const SEED_ADMISSIONS: AdmissionApplication[] = [
  {
    id: "adm-1",
    applicantFirstName: "Ishaan",
    applicantLastName: "Verma",
    dateOfBirth: yearsAgo(6),
    gender: "male",
    guardianName: "Neeraj Verma",
    guardianPhone: "+91 98450 70001",
    appliedClass: "Grade 1",
    status: "pending",
    submittedAt: daysAgo(3),
  },
  {
    id: "adm-2",
    applicantFirstName: "Ananya",
    applicantLastName: "Iyer",
    dateOfBirth: yearsAgo(10),
    gender: "female",
    guardianName: "Kavitha Iyer",
    guardianPhone: "+91 98450 70002",
    appliedClass: "Grade 5",
    status: "pending",
    submittedAt: daysAgo(1),
  },
  {
    id: "adm-3",
    applicantFirstName: "Rehan",
    applicantLastName: "Ahmed",
    dateOfBirth: yearsAgo(14),
    gender: "male",
    guardianName: "Salim Ahmed",
    guardianPhone: "+91 98450 70003",
    appliedClass: "Grade 9",
    status: "waitlisted",
    submittedAt: daysAgo(9),
    notes: "Waitlisted pending seat availability in Grade 9 - A.",
  },
];
