import type { StaffAttendanceSummary, StaffLeaveRequest, StaffMember } from "./types";

const DAY_MS = 1000 * 60 * 60 * 24;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY_MS).toISOString();
const yearsAgo = (n: number) => new Date(Date.now() - n * DAY_MS * 365).toISOString();

export function buildStaffAttendance(staffId: string): StaffAttendanceSummary {
  const recent = Array.from({ length: 14 }).map((_, i) => {
    const offset = 13 - i;
    const dayOfWeek = new Date(Date.now() - offset * DAY_MS).getDay();
    if (dayOfWeek === 0) return { date: daysAgo(offset), status: "holiday" as const };
    const roll = (offset + staffId.length) % 12;
    const status = roll === 0 ? "absent" as const : roll === 6 ? "late" as const : "present" as const;
    return { date: daysAgo(offset), status };
  });
  const present = recent.filter((d) => d.status === "present").length;
  const absent = recent.filter((d) => d.status === "absent").length;
  const late = recent.filter((d) => d.status === "late").length;
  const totalDays = recent.filter((d) => d.status !== "holiday").length;
  return { presentDays: present, absentDays: absent, lateDays: late, totalDays, recent };
}

function salaryOf(basic: number, allowances: number, deductions: number) {
  return { basic, allowances, deductions, bankName: "Union National Bank", bankAccountNumber: "XXXX-XXXX-4821", effectiveFrom: yearsAgo(1) };
}

export const SEED_STAFF: StaffMember[] = [
  {
    id: "stf-1",
    employeeId: "EMP-1001",
    firstName: "Daniel",
    lastName: "Reyes",
    photoUrl: null,
    designation: "Teacher",
    department: "Mathematics",
    status: "active",
    joiningDate: yearsAgo(6),
    dateOfBirth: yearsAgo(34),
    gender: "male",
    phone: "+91 98450 22334",
    email: "teacher@educore.dev",
    address: "18 Cambridge Layout, Bengaluru",
    qualifications: [{ id: "q-1", degree: "M.Sc Mathematics", institution: "University of Bengaluru", yearCompleted: 2014 }],
    experience: [{ id: "e-1", organization: "Greenwood High", role: "Mathematics Teacher", fromYear: 2014, toYear: 2019 }],
    salary: salaryOf(52000, 8000, 2000),
    salaryHistory: [
      { id: "sp-1", month: "2026-06", amountPaid: 58000, paidOn: daysAgo(35) },
      { id: "sp-2", month: "2026-07", amountPaid: 58000, paidOn: daysAgo(5) },
    ],
    documents: [],
    performanceReviews: [
      { id: "pr-1", reviewDate: daysAgo(90), reviewerName: "Meera Iyer", rating: 4, comments: "Consistently strong student engagement and clear lesson delivery." },
    ],
    promotions: [{ id: "pm-1", fromDesignation: "Junior Teacher", toDesignation: "Teacher", effectiveDate: yearsAgo(3), remarks: "Promoted after 3 years of strong performance." }],
  },
  {
    id: "stf-2",
    employeeId: "EMP-1002",
    firstName: "Meera",
    lastName: "Iyer",
    photoUrl: null,
    designation: "Principal",
    department: "Administration",
    status: "active",
    joiningDate: yearsAgo(10),
    dateOfBirth: yearsAgo(48),
    gender: "female",
    phone: "+91 98450 44556",
    email: "meera.iyer@educore.dev",
    address: "3 Lavelle Road, Bengaluru",
    qualifications: [{ id: "q-2", degree: "Ph.D Education", institution: "Delhi University", yearCompleted: 2005 }],
    experience: [{ id: "e-2", organization: "St. Xavier's School", role: "Vice Principal", fromYear: 2010, toYear: 2016 }],
    salary: salaryOf(120000, 20000, 5000),
    salaryHistory: [
      { id: "sp-3", month: "2026-06", amountPaid: 135000, paidOn: daysAgo(35) },
      { id: "sp-4", month: "2026-07", amountPaid: 135000, paidOn: daysAgo(5) },
    ],
    documents: [],
    performanceReviews: [],
    promotions: [],
  },
  {
    id: "stf-3",
    employeeId: "EMP-1003",
    firstName: "Rohan",
    lastName: "Kulkarni",
    photoUrl: null,
    designation: "Accountant",
    department: "Finance",
    status: "active",
    joiningDate: yearsAgo(4),
    dateOfBirth: yearsAgo(31),
    gender: "male",
    phone: "+91 98450 55667",
    email: "rohan.kulkarni@educore.dev",
    address: "56 Indiranagar, Bengaluru",
    qualifications: [{ id: "q-3", degree: "M.Com", institution: "Pune University", yearCompleted: 2017 }],
    experience: [],
    salary: salaryOf(48000, 6000, 1800),
    salaryHistory: [{ id: "sp-5", month: "2026-07", amountPaid: 52200, paidOn: daysAgo(5) }],
    documents: [],
    performanceReviews: [],
    promotions: [],
  },
  {
    id: "stf-4",
    employeeId: "EMP-1004",
    firstName: "Fatima",
    lastName: "Sheikh",
    photoUrl: null,
    designation: "Librarian",
    department: "Library",
    status: "on-leave",
    joiningDate: yearsAgo(3),
    dateOfBirth: yearsAgo(29),
    gender: "female",
    phone: "+91 98450 66778",
    email: "fatima.sheikh@educore.dev",
    address: "9 Frazer Town, Bengaluru",
    qualifications: [{ id: "q-4", degree: "B.Lib", institution: "Karnataka University", yearCompleted: 2019 }],
    experience: [],
    salary: salaryOf(35000, 4000, 1200),
    salaryHistory: [{ id: "sp-6", month: "2026-07", amountPaid: 37800, paidOn: daysAgo(5) }],
    documents: [],
    performanceReviews: [],
    promotions: [],
  },
  {
    id: "stf-5",
    employeeId: "EMP-1005",
    firstName: "James",
    lastName: "Carter",
    photoUrl: null,
    designation: "Teacher",
    department: "Science",
    status: "active",
    joiningDate: yearsAgo(2),
    dateOfBirth: yearsAgo(38),
    gender: "male",
    phone: "+91 98450 77889",
    email: "james.carter@educore.dev",
    address: "27 Whitefield, Bengaluru",
    qualifications: [{ id: "q-5", degree: "B.Ed Science", institution: "Bangalore University", yearCompleted: 2011 }],
    experience: [],
    salary: salaryOf(50000, 7000, 1900),
    salaryHistory: [],
    documents: [],
    performanceReviews: [],
    promotions: [],
  },
  {
    id: "stf-6",
    employeeId: "EMP-1006",
    firstName: "Suresh",
    lastName: "Patil",
    photoUrl: null,
    designation: "Driver",
    department: "Transport",
    status: "active",
    joiningDate: yearsAgo(5),
    dateOfBirth: yearsAgo(42),
    gender: "male",
    phone: "+91 98450 11223",
    email: "suresh.patil@educore.dev",
    address: "14 Yeshwanthpur, Bengaluru",
    qualifications: [],
    experience: [],
    salary: salaryOf(24000, 2000, 800),
    salaryHistory: [],
    documents: [],
    performanceReviews: [],
    promotions: [],
  },
  {
    id: "stf-7",
    employeeId: "EMP-1007",
    firstName: "Geeta",
    lastName: "Naik",
    photoUrl: null,
    designation: "Security",
    department: "Facilities",
    status: "resigned",
    joiningDate: yearsAgo(4),
    dateOfBirth: yearsAgo(45),
    gender: "female",
    phone: "+91 98450 33221",
    email: "geeta.naik@educore.dev",
    address: "2 Malleshwaram, Bengaluru",
    qualifications: [],
    experience: [],
    salary: salaryOf(22000, 1500, 700),
    salaryHistory: [],
    documents: [],
    performanceReviews: [],
    promotions: [],
    resignation: { resignedAt: daysAgo(40), lastWorkingDate: daysAgo(10), reason: "Relocating to another city." },
  },
];

export const SEED_LEAVE_REQUESTS: StaffLeaveRequest[] = [
  {
    id: "sl-1",
    staffId: "stf-4",
    leaveType: "sick",
    fromDate: daysAgo(2),
    toDate: daysAgo(-3),
    reason: "Recovering from a minor surgery.",
    status: "approved",
    requestedAt: daysAgo(5),
  },
  {
    id: "sl-2",
    staffId: "stf-1",
    leaveType: "casual",
    fromDate: daysAgo(-6),
    toDate: daysAgo(-7),
    reason: "Attending a family event.",
    status: "pending",
    requestedAt: daysAgo(0),
  },
];
