import type { SystemUser } from "./types";

const DAY_MS = 1000 * 60 * 60 * 24;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY_MS).toISOString();

const DEFAULT_PREFERENCES = {
  theme: "system" as const,
  language: "en" as const,
  emailNotifications: true,
  smsNotifications: false,
};

export const SEED_USERS: SystemUser[] = [
  {
    id: "usr-1001",
    name: "Ava Whitfield",
    email: "admin@educore.dev",
    phone: "+91 98450 11223",
    roleId: "role-admin",
    department: "Administration",
    status: "active",
    avatarUrl: null,
    createdAt: daysAgo(400),
    lastLoginAt: daysAgo(0),
    preferences: { ...DEFAULT_PREFERENCES },
  },
  {
    id: "usr-1002",
    name: "Daniel Reyes",
    email: "teacher@educore.dev",
    phone: "+91 98450 22334",
    roleId: "role-teacher",
    department: "Mathematics",
    status: "active",
    avatarUrl: null,
    createdAt: daysAgo(320),
    lastLoginAt: daysAgo(0),
    preferences: { ...DEFAULT_PREFERENCES, theme: "light" },
  },
  {
    id: "usr-1003",
    name: "Priya Nair",
    email: "parent@educore.dev",
    phone: "+91 98450 33445",
    roleId: "role-receptionist",
    department: "Front Office",
    status: "active",
    avatarUrl: null,
    createdAt: daysAgo(280),
    lastLoginAt: daysAgo(1),
    preferences: { ...DEFAULT_PREFERENCES },
  },
  {
    id: "usr-1004",
    name: "Meera Iyer",
    email: "meera.iyer@educore.dev",
    phone: "+91 98450 44556",
    roleId: "role-principal",
    department: "Administration",
    status: "active",
    avatarUrl: null,
    createdAt: daysAgo(500),
    lastLoginAt: daysAgo(2),
    preferences: { ...DEFAULT_PREFERENCES },
  },
  {
    id: "usr-1005",
    name: "Rohan Kulkarni",
    email: "rohan.kulkarni@educore.dev",
    phone: "+91 98450 55667",
    roleId: "role-accountant",
    department: "Finance",
    status: "active",
    avatarUrl: null,
    createdAt: daysAgo(210),
    lastLoginAt: daysAgo(4),
    preferences: { ...DEFAULT_PREFERENCES },
  },
  {
    id: "usr-1006",
    name: "Fatima Sheikh",
    email: "fatima.sheikh@educore.dev",
    phone: "+91 98450 66778",
    roleId: "role-librarian",
    department: "Library",
    status: "inactive",
    avatarUrl: null,
    createdAt: daysAgo(150),
    lastLoginAt: daysAgo(45),
    preferences: { ...DEFAULT_PREFERENCES },
  },
  {
    id: "usr-1007",
    name: "James Carter",
    email: "james.carter@educore.dev",
    phone: "+91 98450 77889",
    roleId: "role-teacher",
    department: "Science",
    status: "locked",
    avatarUrl: null,
    createdAt: daysAgo(190),
    lastLoginAt: daysAgo(30),
    preferences: { ...DEFAULT_PREFERENCES },
  },
  {
    id: "usr-1008",
    name: "Neha Gupta",
    email: "neha.gupta@educore.dev",
    phone: "+91 98450 88990",
    roleId: "role-teacher",
    department: "English",
    status: "active",
    avatarUrl: null,
    createdAt: daysAgo(95),
    lastLoginAt: daysAgo(0),
    preferences: { ...DEFAULT_PREFERENCES },
  },
];
