#!/usr/bin/env node
// Seed coverage report: row counts for every table of every service database, per seeded school and branch, with
// anything unexpectedly empty flagged. Local docker stack only - it runs sqlcmd inside the SQL Server container,
// which reads the SA password from its own environment (the password never leaves the container).
//
//   node scripts/seed-demo/coverage.mjs                 # prints a summary, writes loadtest/results/coverage.md
//   node scripts/seed-demo/coverage.mjs --tenant=riverside
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { Session, askPassword } from "./lib.mjs";

const args = Object.fromEntries(process.argv.slice(2).map((a) => { const [k, ...v] = a.replace(/^--/, "").split("="); return [k, v.length ? v.join("=") : "true"]; }));
const CONTAINER = args.container ?? "smsui-sqlserver-1";
const OUT = new URL(args.out ?? "../../loadtest/results/coverage.md", import.meta.url);
const config = JSON.parse(readFileSync(new URL("./seed-config.json", import.meta.url), "utf8"));
const schools = config.tenants.filter((t) => !args.tenant || args.tenant.split(",").includes(t.subdomain)).map((t) => ({ subdomain: t.subdomain, tenantId: `tenant-${t.subdomain}` }));

const DATABASES = { Auth: "AuthServiceDb", Academic: "AcademicServiceDb", Finance: "FinanceServiceDb", Campus: "CampusServiceDb", Engagement: "EngagementServiceDb", Meeting: "MeetingServiceDb" };

// Filled only by real use or infrastructure - empty is expected.
const RUNTIME_ONLY = {
  __EFMigrationsHistory: "migrations",
  AuditLogs: "written by the system", RefreshTokens: "sign-ins", PasswordHistories: "password changes", UserClaims: "unused", UserLogins: "external logins", UserTokens: "unused",
  DismissedRiskFlags: "teacher dismisses an AI risk flag", OnlineExamNotifications: "generated",
  OnlinePayments: "Razorpay checkout",
  BusLiveStatuses: "GPS devices", TicketComments: "help-desk replies",
  ProcessedEvents: "message bus", MobilePushDevices: "mobile app installs", WebPushSubscriptions: "browser push opt-in", DeliveryLogEntries: "generated by broadcasts",
  OutboxMessages: "message bus", OnlineMeetingAuditLogs: "generated", OnlineMeetingReminders: "generated",
  OnlineMeetingAttendance: "live meetings", OnlineMeetingAttendanceSegments: "live meetings", OnlineMeetingChatMessages: "live meetings (chat is only open while running)", OnlineMeetingRecordings: "live meetings",
};

// Tables that belong to a plan-gated module (Permission Matrix names), so a school without it should have none.
const MODULE_OF = {
  Payroll: "Payroll", PayrollRuns: "Payroll", Payslips: "Payroll", SalaryPayments: "Payroll",
  FeeStructures: "Fee Management", FeeInvoices: "Fee Management", FeeDiscounts: "Fee Management", InvoiceInstallments: "Fee Management", Receipts: "Fee Management", Refunds: "Fee Management",
  Accounts: "Accounting", JournalEntries: "Accounting", JournalLines: "Accounting",
  Authors: "Library Management", Publishers: "Library Management", BookCategories: "Library Management", Books: "Library Management", LibraryMembers: "Library Management", BookLoans: "Library Management", BookReservations: "Library Management",
  Buses: "Transport Management", DriverProfiles: "Transport Management", TransportRoutes: "Transport Management", RouteStops: "Transport Management", StudentTransportAssignments: "Transport Management",
  Hostels: "Hostel Management", "Campus.Rooms": "Hostel Management", HostelAllocations: "Hostel Management", HostelAttendanceRecords: "Hostel Management", HostelFeePayments: "Hostel Management", MessMenuEntries: "Hostel Management", VisitorLogs: "Hostel Management",
  ItemCategories: "Inventory Management", Vendors: "Inventory Management", InventoryItems: "Inventory Management", StockTransactions: "Inventory Management",
  HealthCheckups: "Health & Medical", VaccinationRecords: "Health & Medical", InfirmaryVisits: "Health & Medical",
  VisitorEntries: "Visitor Management", PreApprovedVisits: "Visitor Management", WatchlistEntries: "Visitor Management",
  Tickets: "Complaint / Help Desk", IssuedCertificates: "Certificate Generator",
  Surveys: "Surveys & Feedback", SurveyResponses: "Surveys & Feedback",
  BroadcastMessages: "Communication Center", ContactGroups: "Communication Center", MessageTemplates: "Communication Center",
  TalentShowcases: "Talent Showcase", TalentReports: "Talent Showcase", TalentSchoolSettings: "Talent Showcase",
  OnlineExams: "Online Exams", OnlineExamAttempts: "Online Exams", OnlineExamResults: "Online Exams", QuestionBankItems: "Online Exams",
  StudyMaterials: "Study Materials",
  OnlineMeetings: "Online Classes", OnlineMeetingRecurrence: "Online Classes", OnlineMeetingNotes: "Online Classes", OnlineMeetingMaterials: "Online Classes", OnlineMeetingParticipants: "Online Classes", MeetingSchoolSettings: "Online Classes",
};

function sql(db, query) {
  const out = execFileSync("docker", ["exec", "-i", CONTAINER, "bash", "-c", `/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -d ${db} -h -1 -W -s "|" -i /dev/stdin`], { input: `SET NOCOUNT ON;\n${query}`, encoding: "utf8" });
  return out.split(/\r?\n/).map((l) => l.trim()).filter(Boolean).map((l) => l.split("|"));
}

// Every table with its total and whether it carries TenantId / BranchId; then counts per tenant + branch.
const TABLES_SQL = `SELECT t.name, SUM(p.rows), MAX(CASE WHEN c.name='TenantId' THEN 1 ELSE 0 END), MAX(CASE WHEN c.name='BranchId' THEN 1 ELSE 0 END)
FROM sys.tables t JOIN sys.partitions p ON p.object_id = t.object_id AND p.index_id IN (0,1)
LEFT JOIN sys.columns c ON c.object_id = t.object_id AND c.name IN ('TenantId','BranchId') GROUP BY t.name ORDER BY t.name`;
const groupedSql = (tables) =>
  tables
    .map((t) => `SELECT '${t.name}', CAST(TenantId AS nvarchar(100)), ${t.branch ? "CAST(BranchId AS nvarchar(100))" : "NULL"}, COUNT(*) FROM [${t.name}] GROUP BY TenantId${t.branch ? ", BranchId" : ""}`)
    .join("\nUNION ALL\n");

// Plans decide which modules each school should have data for.
const s = new Session("local", args.email ?? "superadmin@educore.dev", await askPassword("SuperAdmin password: "));
await s.login();
const plans = await s.get("identity", "/api/platform/plans");
const tenants = await s.get("identity", "/api/platform/tenants");
for (const sc of schools) {
  const row = tenants.find((x) => x.subdomain === sc.subdomain);
  sc.plan = plans.find((p) => p.id === row?.planId);
  sc.seeded = Boolean(row);
}
const seeded = schools.filter((x) => x.seeded);

const rows = [];
for (const [service, db] of Object.entries(DATABASES)) {
  const tables = sql(db, TABLES_SQL).map(([name, total, tenant, branch]) => ({ name, total: Number(total), tenant: tenant === "1", branch: branch === "1" }));
  const tenantTables = tables.filter((t) => t.tenant && t.total > 0);
  const counts = tenantTables.length ? sql(db, groupedSql(tenantTables)) : [];
  for (const t of tables) {
    const perSchool = {};
    const perBranch = {};
    for (const [name, tenantId, branchId, n] of counts.filter((c) => c[0] === t.name)) {
      const sc = seeded.find((x) => x.tenantId === tenantId);
      if (!sc) continue;
      perSchool[sc.subdomain] = (perSchool[sc.subdomain] ?? 0) + Number(n);
      if (branchId && branchId !== "NULL") perBranch[branchId] = Number(n);
    }
    const module = MODULE_OF[`${service}.${t.name}`] ?? MODULE_OF[t.name];
    const notes = [];
    let status = "ok";
    if (RUNTIME_ONLY[t.name] !== undefined) {
      status = "runtime";
      notes.push(RUNTIME_ONLY[t.name]);
    } else if (t.total === 0) {
      status = "EMPTY";
    } else if (t.tenant) {
      for (const sc of seeded) {
        if (perSchool[sc.subdomain]) continue;
        const inPlan = !module || (sc.plan?.includedModules ?? []).includes(module);
        if (inPlan) {
          status = "GAP";
          notes.push(`none for ${sc.subdomain}`);
        } else notes.push(`${sc.subdomain}: not in plan`);
      }
    } else notes.push("child table (no TenantId)");
    rows.push({ service, ...t, perSchool, perBranch, status, notes });
  }
}

// ── report ───────────────────────────────────────────────────────────────────────────────────
const md = [`# Seed coverage`, ``, `Generated ${new Date().toISOString()} from the local docker databases.`, ``];
md.push(`Schools: ${seeded.map((x) => `**${x.subdomain}** (${x.plan?.name})`).join(", ")}`, ``);
const by = (st) => rows.filter((r) => r.status === st);
md.push(`| Status | Tables |`, `|---|---|`, `| filled | ${by("ok").length} |`, `| gap (in plan, no rows for a school) | ${by("GAP").length} |`, `| empty everywhere | ${by("EMPTY").length} |`, `| runtime-only (expected empty or system-written) | ${by("runtime").length} |`, ``);
for (const service of Object.keys(DATABASES)) {
  md.push(`## ${service}`, ``, `| Table | Total | ${seeded.map((x) => x.subdomain).join(" | ")} | Status | Notes |`, `|---|---:|${seeded.map(() => "---:").join("|")}|---|---|`);
  for (const r of rows.filter((x) => x.service === service)) {
    md.push(`| ${r.name} | ${r.total} | ${seeded.map((x) => (r.tenant ? (r.perSchool[x.subdomain] ?? 0) : "")).join(" | ")} | ${r.status === "ok" ? "✓" : r.status} | ${r.notes.join("; ")} |`);
  }
  md.push(``);
}
mkdirSync(new URL(".", OUT), { recursive: true });
writeFileSync(OUT, md.join("\n"));

console.log(`Tables: ${rows.length} - filled ${by("ok").length}, gaps ${by("GAP").length}, empty ${by("EMPTY").length}, runtime-only ${by("runtime").length}`);
for (const r of [...by("GAP"), ...by("EMPTY")]) console.log(`  ${r.status.padEnd(5)} ${r.service}.${r.name}  ${r.notes.join("; ")}`);
console.log(`Report: ${OUT.pathname.replace(/^\/([A-Z]:)/, "$1")}`);
