// Phase 1 of the Help Center: discovers what the application actually contains, from the source, and writes
//   docs/help/_inventory/inventory.json   machine-readable inventory (routes, nav, per-feature UI facts)
//   docs/help/_inventory/INVENTORY.md     human-readable summary
// Nothing here is hand-maintained: re-run `npm run help:inventory` after the UI changes. The facts are heuristics over the
// source (labels the code renders), so articles are written from them and then verified; the inventory itself proves nothing.
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const src = join(root, "src");
const outDir = join(root, "docs", "help", "_inventory");

const read = (p) => readFileSync(p, "utf8").replace(/\r\n/g, "\n");

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

import { extractFacts, parseNav, parseRoutes, uniq } from "./lib/sources.mjs";

function mergeFacts(a, b) {
  for (const k of Object.keys(b)) {
    if (Array.isArray(b[k])) a[k] = uniq([...(a[k] ?? []), ...b[k]]);
    else a[k] = Boolean(a[k] || b[k]);
  }
  return a;
}

// ── Run ─────────────────────────────────────────────────────────────────────

export function buildInventory() {
  const router = read(join(src, "app", "router.tsx"));
  const routes = parseRoutes(router);
  const nav = parseNav(read(join(src, "constants", "nav.ts")));

  const featuresDir = join(src, "features");
  const features = {};
  for (const dir of readdirSync(featuresDir)) {
    const p = join(featuresDir, dir);
    if (!statSync(p).isDirectory()) continue;
    const files = walk(p).filter((f) => /\.tsx?$/.test(f) && !/\.test\.tsx?$/.test(f));
    const facts = {};
    const perFile = {};
    for (const file of files.filter((f) => f.endsWith(".tsx"))) {
      const fx = extractFacts(read(file));
      perFile[relative(root, file).replace(/\\/g, "/")] = fx;
      mergeFacts(facts, fx);
    }
    features[dir] = {
      files: files.length,
      pages: files.filter((f) => /[\\/]pages[\\/]/.test(f)).map((f) => relative(root, f).replace(/\\/g, "/")),
      facts,
      perFile,
    };
  }

  const routePages = new Map(routes.map((r) => [r.page, r]));
  const sectionOfPath = new Map();
  for (const s of nav.sections) for (const it of s.items) sectionOfPath.set(it.to, s.title);
  const navEntries = [
    ...nav.core.map((it) => ({ ...it, section: null, moduleKey: it.permissionKey })),
    ...nav.sections.flatMap((s) => s.items.map((it) => ({ ...it, section: s.title, moduleKey: it.permissionKey ?? s.permissionKey }))),
  ];

  const navPaths = new Set(navEntries.map((e) => e.to));
  const routesWithoutNav = routes.filter((r) => !navPaths.has(r.path) && !r.path.includes(":")).map((r) => r.path);
  const navWithoutRoute = navEntries.filter((e) => !routes.some((r) => r.path === e.to)).map((e) => e.to);

  return { generatedNote: "Generated by scripts/help/inventory.mjs. Do not edit.", routes, nav, navEntries, features, routePages: [...routePages.keys()], routesWithoutNav, navWithoutRoute, sectionOfPath: Object.fromEntries(sectionOfPath) };
}

function toMarkdown(inv) {
  const out = [];
  out.push("# School Sphere: discovered inventory", "", "_Generated by `scripts/help/inventory.mjs` from the source. Re-run `npm run help:inventory`; do not edit by hand._", "");
  out.push(`- Routes: **${inv.routes.length}** (${inv.routes.filter((r) => !r.path.includes(":")).length} without parameters)`);
  out.push(`- Navigation entries: **${inv.navEntries.length}** in ${inv.nav.sections.length} sections plus ${inv.nav.core.length} top-level entries`);
  out.push(`- Feature folders: **${Object.keys(inv.features).length}**`, "");
  out.push("## Navigation", "", "| Menu | Item | Route | Module key | Audience |", "|---|---|---|---|---|");
  for (const e of inv.navEntries) out.push(`| ${e.section ?? "(top level)"} | ${e.label} | \`${e.to}\` | ${e.moduleKey ?? (e.superAdminOnly ? "super admin only" : "any signed-in user")} | ${e.audience ?? "all"} |`);
  out.push("", "## Routes", "", "| Path | Page component | Guard |", "|---|---|---|");
  for (const r of inv.routes) out.push(`| \`${r.path}\` | ${r.page ?? "?"} | ${r.requires ?? "signed in"} |`);
  out.push("", "## Routes with no navigation entry (reached from inside other screens or by link)", "");
  for (const p of inv.routesWithoutNav) out.push(`- \`${p}\``);
  if (inv.navWithoutRoute.length) out.push("", "## Navigation entries with no matching route", "", ...inv.navWithoutRoute.map((p) => `- \`${p}\``));
  out.push("", "## Per-feature UI facts (labels the code renders)", "");
  for (const [name, f] of Object.entries(inv.features)) {
    const x = f.facts;
    out.push(`### ${name}`, "", `${f.files} source files, ${f.pages.length} page file(s)`);
    for (const [k, label] of [["tabs", "Tabs"], ["buttons", "Buttons"], ["dialogs", "Dialogs"], ["confirms", "Confirmations"], ["requiredLabels", "Required fields"], ["labels", "Field labels"], ["columns", "Table columns"], ["menuActions", "Row menu actions"], ["toastsSuccess", "Success messages"], ["validation", "Validation messages"]]) {
      if (x[k]?.length) out.push(`- **${label}:** ${x[k].slice(0, 40).join(" · ")}${x[k].length > 40 ? " …" : ""}`);
    }
    out.push("");
  }
  return out.join("\n");
}

if (process.argv[1] && process.argv[1].endsWith("inventory.mjs")) {
  const inv = buildInventory();
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "inventory.json"), JSON.stringify(inv, null, 2) + "\n");
  writeFileSync(join(outDir, "INVENTORY.md"), toMarkdown(inv) + "\n");
  console.log(`Inventory: ${inv.routes.length} routes, ${inv.navEntries.length} nav entries, ${Object.keys(inv.features).length} features -> ${relative(root, outDir)}`);
}
